### ISSUE TITLE
Too long headings

### ISSUE THREAD

**Issue by KgrInklusio** [skotkjerra/Inklusio--Website#80]
Headings placed above text content should be shortened to prevent overflow and remain within the same visual area as the text below them. Se examples below: 

'<img width="756" alt="image" src="https://user-images.githubusercontent.com/87171286/233058609-5d21a0ed-6a30-49c2-a994-778ae9f54920.png">
![image](https://user-images.githubusercontent.com/87171286/233058799-e8bacd33-e8b4-46ea-afb0-ba7ffb3da056.png)

**Comment by KgrInklusio** [comment]
I still find the headers a bit too wide. They should not be wider than the bodytext below them.  
<img width="683" alt="image" src="https://github.com/skotkjerra/Inklusio--Website/assets/87171286/14ec3539-c144-49eb-aecd-929eb8b4ea61">

**Comment by KgrInklusio** [comment]
I am still encountering instances where the headers appear wider than the content located below them. An example of this being done **as wished** can be found in the last sections of the "Lær mere" page. Specifically, the statement "Vi arbejder tæt sammen med personer med handicap" maintains a proportional width with the content beneath it. This is the visual consistency I am aiming for across all content sections. The width of a header should never exceed that of the content below it. Feel free to reach out if you need any further clarification on this matter. 

![image](https://github.com/skotkjerra/Inklusio--Website/assets/87171286/1ce95c4b-dba2-41ab-aa56-6bc2fdc0b498)

**Comment by abdul789150** [comment]
Hi Katrine, I've updated the headings and verified their consistency across all screen sizes. If you come across any problems, please inform me, and please include the screen size as well so that I can make the necessary adjustments.
