### ISSUE TITLE
Footer alterations 

### ISSUE THREAD

**Issue by KgrInklusio** [skotkjerra/Inklusio--Website#82]
I have made some alterations to the footer that I kindly ask you to implement. See attached image for reference: 

The link to our LinkedIn: https://www.linkedin.com/company/inklusio 
![image](https://user-images.githubusercontent.com/87171286/233067421-bf30d40f-7600-4461-95fe-bb762da34a42.png)

**Comment by abdul789150** [comment]
Sure, I will update the footer as per the attached image, and kindly provide the LinkedIn icon used in the reference image for the footer.

**Comment by abdul789150** [comment]
Thank you so much for providing the icon, and I will resolve all the design issues and update the website as soon as possible.

**Comment by KgrInklusio** [comment]
<img width="826" alt="image" src="https://github.com/skotkjerra/Inklusio--Website/assets/87171286/be87aeda-6fe5-412c-916d-cf5d37bdf344">

**Comment by KgrInklusio** [comment]
Hello Abdul, 
I find that the footer is way too tall. I have corrected the design to be less bulky. Please let me know if this can be corrected within the budget.

**Comment by KgrInklusio** [comment]
"Tlf." should not be bold :) 

![image](https://github.com/skotkjerra/Inklusio--Website/assets/87171286/c7d1b2fe-2b24-49c3-9c53-0aff8324219f)
