### ISSUE TITLE
Image rounded corners in top corners but not bottom corners

### ISSUE THREAD

**Issue by annethyme** [skotkjerra/Inklusio--Website#89]
On the home page, the image in the grey area has rounded corners in the top corners but not the bottom corners. 
And the radius of the rounding is quite different from the one used for the image further down. 

(And in general, it would be nice if all images on our tiny website was styled the same, but I guess this is a bit out of scope for now).

**Comment by 2biazdk** [comment]
Fixed in Dev branch. :-)
