### ISSUE TITLE
Uniform margins and appearance 

### ISSUE THREAD

**Issue by KgrInklusio** [skotkjerra/Inklusio--Website#91]
Currently, the content on the webpage is not aligned uniformly, and I believe that implementing even margins/padding and a grid-like structure would significantly improve the overall user experience. 

The margins on the left and right sides of the content are not consistent all the way down the page, leading to an uneven appearance. I want the margin even on the left hand side following the start of the top left logo and I want the content to reflow the same in the right hand side for an even appearance - see attached images. Please ensure this is true for all screen sizes and all the pages of the website, because in the blogs section it is a whole different margin. I wish to have a uniform appearance across all pages. 

https://lidtlakrids.dk/ is a good example of a webpage that has a uniform structure and even margin/padding on each side.

![image](https://github.com/skotkjerra/Inklusio--Website/assets/87171286/087771d3-daa2-4fd9-9424-f3d2937f70f9)
![image](https://github.com/skotkjerra/Inklusio--Website/assets/87171286/95e0861f-7d50-455a-8aa6-01c4ed163e1a)

**Comment by abdul789150** [comment]
Hi Katrine, I've adjusted the uniform margins and appearance to ensure consistency across all pages and screen sizes. Please review these changes. If you notice any discrepancies or issues, let me know and I'll fix them.
